<a href="https://colab.research.google.com/github/kl2400032181/2400032181-DataScience-Experiments/blob/main/Experiment_8_%E2%80%94_Linear_Algebra_%26_Matrix_Decomposition_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create two vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Vector addition
addition = A + B

# Vector subtraction
subtraction = A - B

# Scalar multiplication
scalar = 3
scalar_multiplication = scalar * A

# Dot product
dot_product = np.dot(A, B)

# Magnitude of vectors
magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

# Display results
print("Vector A:", A)
print("Vector B:", B)

print("\nVector Addition:", addition)
print("Vector Subtraction:", subtraction)
print("Scalar Multiplication:", scalar_multiplication)
print("Dot Product:", dot_product)

print("Magnitude of Vector A:", magnitude_A)
print("Magnitude of Vector B:", magnitude_B)

Vector A: [1 2 3]
Vector B: [4 5 6]

Vector Addition: [5 7 9]
Vector Subtraction: [-3 -3 -3]
Scalar Multiplication: [3 6 9]
Dot Product: 32
Magnitude of Vector A: 3.7416573867739413
Magnitude of Vector B: 8.774964387392123


In [2]:
import numpy as np

# Create a square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

# Calculate determinant
determinant = np.linalg.det(A)

# Calculate rank
rank = np.linalg.matrix_rank(A)

# Calculate trace
trace = np.trace(A)

# Display matrix
print("Matrix A:")
print(A)

# Display results
print("\nDeterminant:", determinant)
print("Rank:", rank)
print("Trace:", trace)

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Determinant: -2.9999999999999996
Rank: 3
Trace: 16


In [3]:
import numpy as np

# Create a square matrix
A = np.array([
    [4, 1],
    [2, 3]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display matrix
print("Matrix A:")
print(A)

# Display eigenvalues
print("\nEigenvalues:")
print(eigenvalues)

# Display eigenvectors
print("\nEigenvectors:")
print(eigenvectors)

Matrix A:
[[4 1]
 [2 3]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [4]:
import numpy as np

# Create a matrix
A = np.array([
    [4, 1],
    [2, 3]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Select the first eigenvalue and corresponding eigenvector
lambda_value = eigenvalues[0]
v = eigenvectors[:, 0]

# Calculate Av
Av = A @ v

# Calculate lambda * v
lambda_v = lambda_value * v

# Display results
print("Matrix A:")
print(A)

print("\nEigenvalue:", lambda_value)
print("\nEigenvector:", v)

print("\nA @ v:")
print(Av)

print("\nLambda * v:")
print(lambda_v)

# Verify the relationship
if np.allclose(Av, lambda_v):
    print("\nAv = λv is verified.")
else:
    print("\nAv = λv is not verified.")

Matrix A:
[[4 1]
 [2 3]]

Eigenvalue: 5.0

Eigenvector: [0.70710678 0.70710678]

A @ v:
[3.53553391 3.53553391]

Lambda * v:
[3.53553391 3.53553391]

Av = λv is verified.


In [5]:
import numpy as np
from scipy.linalg import lu

# Create a square matrix
A = np.array([
    [4, 3],
    [6, 3]
])

# Perform LU decomposition
P, L, U = lu(A)

# Display results
print("Matrix A:")
print(A)

print("\nPermutation Matrix P:")
print(P)

print("\nLower Triangular Matrix L:")
print(L)

print("\nUpper Triangular Matrix U:")
print(U)

Matrix A:
[[4 3]
 [6 3]]

Permutation Matrix P:
[[0. 1.]
 [1. 0.]]

Lower Triangular Matrix L:
[[1.         0.        ]
 [0.66666667 1.        ]]

Upper Triangular Matrix U:
[[6. 3.]
 [0. 1.]]


In [6]:
import numpy as np

# Create a symmetric positive definite matrix
A = np.array([
    [4, 2],
    [2, 3]
])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)

# Display matrix
print("Matrix A:")
print(A)

# Display lower triangular matrix
print("\nLower Triangular Matrix L:")
print(L)

# Verify A = L @ L.T
print("\nL @ L.T:")
print(L @ L.T)

Matrix A:
[[4 2]
 [2 3]]

Lower Triangular Matrix L:
[[2.         0.        ]
 [1.         1.41421356]]

L @ L.T:
[[4. 2.]
 [2. 3.]]


In [7]:
import numpy as np

# Create a matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Perform QR decomposition
Q, R = np.linalg.qr(A)

# Display matrix
print("Matrix A:")
print(A)

# Display Q
print("\nOrthogonal Matrix Q:")
print(Q)

# Display R
print("\nUpper Triangular Matrix R:")
print(R)

# Verify A = Q @ R
print("\nQ @ R:")
print(Q @ R)

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Orthogonal Matrix Q:
[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]

Upper Triangular Matrix R:
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]

Q @ R:
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [8]:
import numpy as np

# Create a matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Create Sigma matrix
Sigma = np.zeros((U.shape[1], VT.shape[0]))
np.fill_diagonal(Sigma, S)

# Display original matrix
print("Matrix A:")
print(A)

# Display U
print("\nMatrix U:")
print(U)

# Display singular values
print("\nSingular Values:")
print(S)

# Display Sigma
print("\nSigma Matrix:")
print(Sigma)

# Display V transpose
print("\nMatrix V^T:")
print(VT)

# Verify A = U @ Sigma @ VT
print("\nReconstructed Matrix:")
print(U @ Sigma @ VT)

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Matrix U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular Values:
[9.52551809 0.51430058]

Sigma Matrix:
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

Matrix V^T:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Reconstructed Matrix:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
